plugin:
    name: 'chladek.composers::lang.plugin.name'
    description: 'chladek.composers::lang.plugin.description'
    author: chladek
    icon: oc-icon-music
    homepage: ''
navigation:
    main-menu-item:
        label: Composers
        url: chladek/composers/composers
        icon: icon-music
